version: '3'
services:
  db:
    image: 'postgres'
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: squadify_db
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on: 
      - "db"
    ports:
      - "3000:3000"